name: Print comment event

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr_diff:
    runs-on: ubuntu-latest

    steps:
    - name: Print Event
      run: |
        echo "Event: ${{ toJSON(github.event) }}"
